project:
  type: website
  output-dir: _site

website:
  title: "Yichen Liu"
  site-url: "https://nehciyl.github.io/"
  description: "PhD candidate in finance."
  back-to-top-navigation: true
  navbar:
    pinned: true
    left:
      - icon: house-door
        text: Home
        href: index.qmd
      - icon: file-person
        text: About
        href: about.qmd
      - icon: journal-text
        text: Research
        href: research.qmd
      - icon: easel
        text: Teaching
        href: teaching.qmd
    tools:
      - icon: mortarboard
        href: "https://orcid.org/0009-0001-8822-1929"
      - icon: github
        href: "https://github.com/NehciyL"
  page-footer:
    left: "Yichen Liu © 2026"
    center:
      - icon: envelope
        href: "mailto:yichen1.liu@skema.edu"
      - icon: linkedin
        href: "https://www.linkedin.com/in/yichen-l-a84246105"
    right: "Built with [Quarto](https://quarto.org/)"
  open-graph: true

format:
  html:
    theme: theme.scss
    include-in-header: header.html
    toc: false
    anchor-sections: false
    link-external-newwindow: true